"""agent gateway expansion

Revision ID: e18980b9af49
Revises: 0007
Create Date: 2026-09-09 14:58:23.338466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e18980b9af49'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    sa.Enum('remote_http', 'a2a', name='agent_protocol').create(bind, checkfirst=True)
    sa.Enum('private', 'published', name='agent_visibility').create(bind, checkfirst=True)
    sa.Enum('unknown', 'healthy', 'unhealthy', name='agent_health_status').create(bind, checkfirst=True)

    op.create_table('agent_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_pricing',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('cost_per_invocation', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('agent_project_enablements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('enabled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enabled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'project_id', name='uq_agent_project_enablement')
    )
    op.create_table('agent_approval_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_approval_tasks', sa.Column('assigned_reviewer_user_id', sa.UUID(), nullable=True))
    op.add_column('agent_approval_tasks', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_approval_tasks', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'agent_approval_tasks',
        sa.Column('evidence_links', sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    )
    op.add_column(
        'agent_approval_tasks',
        sa.Column('submission_round', sa.Integer(), server_default=sa.text('1'), nullable=False),
    )
    op.create_foreign_key(None, 'agent_approval_tasks', 'users', ['assigned_reviewer_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('agent_invocations', sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column(
        'agents',
        sa.Column(
            'protocol',
            sa.Enum('remote_http', 'a2a', name='agent_protocol'),
            server_default='remote_http',
            nullable=False,
        ),
    )
    op.add_column(
        'agents',
        sa.Column(
            'visibility',
            sa.Enum('private', 'published', name='agent_visibility'),
            server_default='published',
            nullable=False,
        ),
    )
    op.add_column('agents', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('agents', sa.Column('deprecation_notice', sa.Text(), nullable=True))
    op.add_column(
        'agents',
        sa.Column(
            'health_status',
            sa.Enum('unknown', 'healthy', 'unhealthy', name='agent_health_status'),
            server_default='unknown',
            nullable=False,
        ),
    )
    op.add_column('agents', sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'agents',
        sa.Column('current_submission_round', sa.Integer(), server_default=sa.text('0'), nullable=False),
    )
    op.create_foreign_key(None, 'agents', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'current_submission_round')
    op.drop_column('agents', 'last_heartbeat')
    op.drop_column('agents', 'health_status')
    op.drop_column('agents', 'deprecation_notice')
    op.drop_column('agents', 'project_id')
    op.drop_column('agents', 'visibility')
    op.drop_column('agents', 'protocol')
    op.drop_column('agent_invocations', 'cost_usd')
    op.drop_constraint(None, 'agent_approval_tasks', type_='foreignkey')
    op.drop_column('agent_approval_tasks', 'submission_round')
    op.drop_column('agent_approval_tasks', 'evidence_links')
    op.drop_column('agent_approval_tasks', 'escalated_at')
    op.drop_column('agent_approval_tasks', 'due_at')
    op.drop_column('agent_approval_tasks', 'assigned_reviewer_user_id')
    op.drop_table('agent_approval_comments')
    op.drop_table('agent_project_enablements')
    op.drop_table('agent_pricing')
    op.drop_table('agent_audit_log')
    # ### end Alembic commands ###

    bind = op.get_bind()
    sa.Enum(name='agent_health_status').drop(bind, checkfirst=True)
    sa.Enum(name='agent_visibility').drop(bind, checkfirst=True)
    sa.Enum(name='agent_protocol').drop(bind, checkfirst=True)
