"""initial schema

Revision ID: 2e452ff8ad8e
Revises: 
Create Date: 2026-08-27 07:34:51.671072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e452ff8ad8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_services',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('authentication_type', sa.Enum('none', 'api_key', 'bearer', 'basic', 'oauth2_client_credentials', name='rest_auth_type'), nullable=False),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rate_limit_per_window', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='api_service_status'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mcp_servers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('transport_type', sa.Enum('http', name='mcp_transport_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='mcp_server_status'), nullable=False),
    sa.Column('health_status', sa.Enum('unknown', 'healthy', 'unhealthy', name='mcp_health_status'), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('protocol_version', sa.String(), nullable=True),
    sa.Column('last_sync_status', sa.Enum('pending', 'success', 'error', name='mcp_sync_status'), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_latency_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_pricing',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'bedrock', name='provider_name'), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_per_1k', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('completion_per_1k', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model')
    )
    op.create_table('organizations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('provider_configs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'bedrock', name='provider_name'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('credential_ref', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'display_name')
    )
    op.create_table('secrets',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant', sa.String(), nullable=False),
    sa.Column('secret_name', sa.String(), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'secret_name', name='uq_secrets_tenant_secret_name')
    )
    op.create_table('tenant_identity_config',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('keycloak', 'entra', 'auth0', 'okta', 'aws_identity', 'google', name='identity_provider_name'), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('api_endpoints',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('api_service_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', name='rest_http_method'), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_service_id'], ['api_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_name')
    )
    op.create_table('projects',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('identity_provider', sa.Enum('keycloak', 'entra', 'auth0', 'okta', 'aws_identity', 'google', name='identity_provider_name'), nullable=False),
    sa.Column('external_sub', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'team_lead', 'developer', 'viewer', name='user_role'), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identity_provider', 'external_sub')
    )
    op.create_table('access_policies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('allowed_roles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('allowed_identity_providers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('allowed_tool_names', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('allowed_agent_keys', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('agent_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_team', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('capabilities', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('risk_class', sa.Enum('low', 'medium', 'high', name='agent_risk_class'), nullable=False),
    sa.Column('trust_level', sa.Enum('t0_unknown', 't1_registered_internal', 't2_enterprise_trusted', 't3_privileged', 't4_approved_external_partner', 't5_public_untrusted', name='agent_trust_level'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'validating', 'under_review', 'approved', 'published', 'active', 'suspended', 'deprecated', 'retired', 'rejected', name='agent_lifecycle_status'), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('card', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_key')
    )
    op.create_table('api_keys',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('hashed_key', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_key')
    )
    op.create_table('budgets',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('period', sa.Enum('daily', 'monthly', name='budget_period'), nullable=False),
    sa.Column('limit_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('alert_threshold_pct', sa.Integer(), nullable=False),
    sa.CheckConstraint('organization_id IS NOT NULL OR project_id IS NOT NULL OR user_id IS NOT NULL', name='chk_budget_scope'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_tools',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_type', sa.Enum('mcp', 'rest', name='mcp_tool_source_type'), nullable=False),
    sa.Column('server_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('api_endpoint_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source_type = 'mcp' AND server_id IS NOT NULL AND api_endpoint_id IS NULL) OR (source_type = 'rest' AND api_endpoint_id IS NOT NULL AND server_id IS NULL)", name='chk_mcp_tool_source'),
    sa.ForeignKeyConstraint(['api_endpoint_id'], ['api_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_users_one_active', 'project_users', ['project_id', 'user_id'], unique=True, postgresql_where=sa.text('end_date IS NULL'))
    op.create_table('routing_rules',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_alias', sa.String(), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('capability', sa.Enum('chat', 'embedding', name='model_capability'), nullable=False),
    sa.Column('strategy', sa.Enum('priority', 'cost', 'latency', name='routing_strategy'), nullable=False),
    sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_audit_log',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('operation', sa.Enum('get', 'set', 'delete', 'rotate', name='secret_operation'), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('secret_name', sa.String(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('success', 'error', name='secret_audit_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_approval_tasks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('agent_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('stage', sa.Enum('security', 'technical', 'business', 'data_governance', 'production', name='agent_approval_stage'), nullable=False),
    sa.Column('decision', sa.Enum('pending', 'approved', 'rejected', name='agent_approval_decision'), nullable=False),
    sa.Column('approver_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_invocations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('api_key_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('agent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('authorization_decision', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('success', 'error', 'blocked', 'rate_limited', name='request_status'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('mcp_request_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('api_key_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('client_session_id', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('server_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('execution_type', sa.Enum('mcp', 'rest', name='mcp_tool_source_type'), nullable=True),
    sa.Column('api_service_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('endpoint_path', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('success', 'error', 'blocked', 'rate_limited', name='request_status'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['api_service_id'], ['api_services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('mcp_sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('client_session_id', sa.String(), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('api_key_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('server_sessions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_session_id')
    )
    op.create_table('request_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('api_key_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_alias', sa.String(), nullable=False),
    sa.Column('capability', sa.Enum('chat', 'embedding', name='model_capability'), nullable=False),
    sa.Column('resolved_provider', sa.String(), nullable=True),
    sa.Column('resolved_model', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('success', 'error', 'blocked', 'rate_limited', name='request_status'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('cost_ledger',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('request_log_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_log_id'], ['request_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardrail_results',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('request_log_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('direction', sa.Enum('prompt', 'response', name='guardrail_direction'), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_log_id'], ['request_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guardrail_results')
    op.drop_table('cost_ledger')
    op.drop_table('request_logs')
    op.drop_table('mcp_sessions')
    op.drop_table('mcp_request_logs')
    op.drop_table('agent_invocations')
    op.drop_table('agent_approval_tasks')
    op.drop_table('secret_audit_log')
    op.drop_table('routing_rules')
    op.drop_index('idx_project_users_one_active', table_name='project_users', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_table('project_users')
    op.drop_table('mcp_tools')
    op.drop_table('budgets')
    op.drop_table('api_keys')
    op.drop_table('agents')
    op.drop_table('access_policies')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('api_endpoints')
    op.drop_table('tenant_identity_config')
    op.drop_table('secrets')
    op.drop_table('provider_configs')
    op.drop_table('organizations')
    op.drop_table('model_pricing')
    op.drop_table('mcp_servers')
    op.drop_table('api_services')
    # ### end Alembic commands ###
